#!/usr/bin/env ruby

$:.unshift File.expand_path('../lib', __dir__)
require 'xremap'

if ARGV.size != 1
  abort "Usage: #{$0} config.rb"
end

source = File.read(ARGV.first)
dsl = Xremap::DSL.new
dsl.instance_eval(source)
puts Xremap.generate(dsl)
